# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html






title: 2022 CoG Robomaster Sim2Real Challenge
short_description: This competition is themed around EP robots, and we will provide simulation environments and real life scenarios. Robots need to continuously search for sequential QR codes in a specified map, while avoiding collisions with static obstacles and other moving robots in the environment. The robot that completes the search for the QR code in the fastest and safest way will win the competition. There are two tracks, the first one is simpler, which is investigates the basic algorithm, the second one is more difficult, which is investigates some reinforcement learning algorithms. We will provide a simulation environment which can be used by reinforcement learning algorithms and other learning algorithms. We will provide motion planning、localization、shutting、rule decision and reinforcement learning baseline algorithms. The competition will be divided into three stages. In the first stage, the competition will be carried out in the simulation environment, in the second stage, the competition will be carried out in the actual robot field, and in the third stage, the scheme defense will be carried out.
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: <p style="color:#FFCA2C">In order to better display the evaluation results, please click <a href="https://ieee-cog.org/2022/cog_sim2real/index.html">https://ieee-cog.org/2022/cog_sim2real/index.html</a> to jump to the relevant webpage. </p>
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2022-04-01 00:00:00
end_date: 2022-08-15 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["Metric1", "Metric2", "Metric3", "Total"],
        "default_order_by": "Total",
        "metadata": {
          "Metric1": {
            "sort_ascending": True,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          },
          "Metric2": {
            "sort_ascending": True,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          }
        }
      }

# leaderboard:
#   - id: 1
#     schema:
#       {
# #         "labels": ["Easy_Nav_T", "Easy_activated_goal", "Easy_remain_HP", "Easy_demage", "Easy_collision_punishment", "Easy_time", "Easy_score", "Middle_Nav_T", "Middle_activated_goal", "Middle_remain_HP", "Middle_demage", "Middle_collision_punishment", "Middle_time", "Middle_score","Hard_Nav_T", "Hard_activated_goal", "Hard_remain_HP", "Hard_demage", "Hard_collision_punishment", "Hard_time", "Hard_score","Mean_activated_goal", "Score"],
#         "labels": ["Easy_Nav_T"],
# #         "default_order_by": "Score",
#         "default_order_by": "Easy_Nav_T",
#         "metadata": {
#           "Easy_Nav_T": {
#             "sort_ascending": True,
#             "description": "",
#           },
# #           "Easy_activated_goal": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Easy_remain_HP": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Easy_demage": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Easy_collision_punishment": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Easy_time": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },"Easy_score": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Middle_Nav_T": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Middle_activated_goal": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Middle_remain_HP": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Middle_demage": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Middle_collision_punishment": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Middle_time": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Middle_score": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Hard_Nav_T": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Hard_activated_goal": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Hard_remain_HP": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Hard_demage": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Hard_collision_punishment": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Hard_time": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Hard_score": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Mean_activated_goal": {
# #             "sort_ascending": True,
# #             "description": "",
# #           },
# #           "Score": {
# #             "sort_ascending": True,
# #             "description": "",
# #           }
#         }
#       }


      
challenge_phases:
  - id: 1
    name: SimulationPhase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2022-05-10 00:00:00
    end_date: 2022-06-17 23:59:59
    test_annotation_file: annotations/test_annotations_devsplit.json
    codename: dev
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 100
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: TextAttribute
        description: Notes on running code
        type: text
        required: True
      - name: Track_Choose
        description: which track do you prefer?
        type: radio
        required: True
        options: ["Track 1", "Track 2"]
        
#       - name: MultipleChoiceAttribute
#         description: Sample
#         type: checkbox
#          required: False
#         options: ["alpha", "beta", "gamma"]
#       - name: TrueFalseField
#         description: Sample
#         type: boolean
#         required: False

    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".json, .zip, .txt, .tsv, .gz, .csv, .h5, .npy, .npz"
#      allowed_submission_file_types: ".txt"
      
    
  - id: 2
    name: PhysicalPhase
    description: templates/challenge_phase_2_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2022-06-20 00:00:00
    end_date: 2022-07-30 23:59:59
    test_annotation_file: annotations/test_annotations_devsplit.json
    codename: dev
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 100
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: TextAttribute
        description: Sample
        type: text
        required: False
      - name: SingleOptionAttribute
        description: Sample
        type: radio
         required: False
        options: ["A", "B", "C"]
      - name: MultipleChoiceAttribute
        description: Sample
        type: checkbox
         required: False
        options: ["alpha", "beta", "gamma"]
      - name: Track_Choose
        description: which track do you prefer?
        type: radio
        required: True
        options: ["Track 1", "Track 2"]
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".json, .zip, .txt, .tsv, .gz, .csv, .h5, .npy, .npz"
    
dataset_splits:
  - id: 1
    name: Train Split
    codename: train_split
  - id: 2
    name: Test Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
